name: Destroy AWS Resouces
on:
  workflow_dispatch:
    inputs:
      region:
        description: "Enter Region : "
        required: true
        type: string
env:
  ENV: dev
  BUCKET_NAME: aws-msr-dev-devops-state
  TF_VAR_STATE_FILE: $ENV-${{ github.event.repository.name }}.tfstate
  REGION: ${{ github.event.inputs.region }}
defaults:
  run:
    shell: bash
jobs:
  terraform:
    name: Destroy AWS Resouces
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}
          
      - name: Terraform Init
        run: terraform init -no-color -reconfigure -force-copy
          -backend-config="bucket=$BUCKET_NAME" -backend-config="key=${{
          env.TF_VAR_STATE_FILE }}"  -backend-config="region=${{ env.REGION}}"
      
      - name: Terraform Destroy     
        run: terraform destroy -auto-approve -input=false -lock=false
